services:
  - type: web
    name: mensualidad-27-pro
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mensualidad-db
          property: connectionString

databases:
  - name: mensualidad-db
    databaseName: mensualidad
    user: admin
